name:                HilbertCurve
version:             0.1.0.0
github:              "githubuser/HilbertCurve"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         A Hilbert curve implementation in Haskell

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  HilbertCurve-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HilbertCurve
    - hspec
